### ISSUE TITLE
Ignore a missing equipment in unsetslot

### ISSUE THREAD

**Issue by kcaa** [kcaa/kcaa#237]
When a new item comes, /api_get_member/unsetslot may come first with a new item in the list. At this timing the it might not see /api_get_member/slot_item yet.

Thus resulting:

    12:24:53 DEBUG: Accessed KCSAPI: /api_get_member/unsetslot
    12:24:53 ERROR: Traceback (most recent call last):
      File "/home/eplusx/kcaa/server/kcaa/kcsapi_util.py", line 320, in dispatch
        self.debug)
      File "/home/eplusx/kcaa/server/kcaa/kcsapi/equipment.py", line 280, in update
        self.items[str(equipment_id)].in_type_index = i
    KeyError: '28559'

    12:24:54 DEBUG: Accessed KCSAPI: /api_get_member/slot_item
    12:24:55 DEBUG: Accessed KCSAPI: /api_get_member/unsetslot
    12:24:56 DEBUG: Unknown KCSAPI:  /api_get_member/useitem
    12:24:56 DEBUG: Accessed KCSAPI: /api_port/port

At least for the new items found in the event rewards, unsetslot is duplicated after slot_item. Probably safe to ignore.

**Comment by kcaa** [comment]
f53c5333a6bab306fb7209437e7b448342516348
