### ISSUE TITLE
Fix the screen after finishing the remodeling

### ISSUE THREAD

**Issue by kcaa** [kcaa/kcaa#262]
GoOnExpedition wanted to change the screen, but it didn't work:

    15:01:44 DEBUG: Manipulator queue: [GoOnExpedition (p-42;c92), WarmUp (p-42;c93)
    ]
    15:01:44 DEBUG: Manipulator GoOnExpedition started.
    15:01:44 INFO : Making the fleet 1 go on the expedition 1-1 with the formation 0

    15:01:44 ERROR: TypeError: This operation cannot be done. Expected: 212, Current
    : 21201
    15:01:44 DEBUG: Traceback (most recent call last):
      File "Z:\kcaa\server\kcaa\task.py", line 283, in update
        delay = self._iterator.next()
      File "Z:\kcaa\server\kcaa\manipulators\expedition.py", line 70, in run
        yield self.screen.change_screen(screens.PORT_EXPEDITION)
      File "Z:\kcaa\server\kcaa\manipulators\screen.py", line 684, in change_screen
        self.assert_screen(screens.PORT_REBUILDING)
      File "Z:\kcaa\server\kcaa\manipulators\screen.py", line 77, in assert_screen
        .format(screen_id, self.screen_id))
    TypeError: This operation cannot be done. Expected: 212, Current: 21201

**Comment by kcaa** [comment]
5b67c0cd7bff8c595955bf0bca7a05e378331684
